Deploy_script_fix_9

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -58,9 +58,9 @@ jobs:
           sleep 10 # wait for server to properly start
           
           # My own server's healthcheck endpoint
-          HEALTHCHECK_URL="http://${{ secrets.EC2_HOST }}:3000/health"
+          HEALTHCHECK_URL=`http://52.59.130.11:3000/health`
           echo "Healthcheck URL: $HEALTHCHECK_URL"
-          curl -v $HEALTHCHECK_URL || echo "❌ Curl failed"
+          curl -v http://52.59.130.11:3000/health || echo "❌ Curl failed"
 
           if curl --fail --silent $HEALTHCHECK_URL; then
             echo "✅ Server is healthy. Deployment complete!"
